In [12]:
!pip install opencv-python
import cv2
import keras

In [13]:
import numpy as np

In [14]:
PETS = ['Cat','Dog']

def image(path):
    print(path)
    img = cv2.imread(path,cv2.IMREAD_GRAYSCALE)
    print(img)
    try:
        img = cv2.resize(img,(100,100))
    except cv2.error as e:
        print("Invalid Image")
    img = np.array(img)
    img = img.reshape(-1,100,100,1)
    print(img.shape)
    return img


In [15]:
model = keras.models.load_model('Tuning.model')

In [17]:
prediction = model.predict([image('C:\Gows\Testing\Dog.jpg')])
print(PETS[prediction.argmax()])

C:\Gows\Testing\Dog.jpg
[[255 211 199 ... 201 208 210]
 [222 157 125 ... 107 106 104]
 [237 157 110 ...  93  88  86]
 ...
 [254 251 248 ... 238 238 240]
 [254 253 251 ... 244 244 245]
 [253 253 253 ... 249 248 249]]
(1, 100, 100, 1)
Dog
