In [1]:
import pickle

In [2]:
F = pickle.load(open('F.pkl','rb'))
L = pickle.load(open('L.pkl','rb'))

In [3]:
F

array([[[123, 121, 118, ...,  31,  40,  35],
        [144, 132, 114, ...,  36,  53,  45],
        [153, 146, 150, ...,  49,  47,  55],
        ...,
        [138, 118,  78, ..., 139, 107,  56],
        [142, 145, 147, ..., 162,  98,  48],
        [148, 151, 148, ..., 124,  90,  54]],

       [[252, 251, 253, ..., 254, 250, 251],
        [183, 212, 206, ..., 198, 201, 212],
        [179, 253, 255, ..., 254, 253, 253],
        ...,
        [142, 134, 131, ..., 110,  85, 142],
        [130, 125, 124, ..., 107,  84, 157],
        [120, 120, 122, ..., 120,  95, 151]],

       [[ 58,  58,  58, ...,  97,  97,  97],
        [ 58,  58,  58, ...,  97,  97,  97],
        [ 58,  58,  58, ...,  97,  97,  97],
        ...,
        [ 76,  78,  79, ..., 146, 143, 143],
        [ 85,  87,  91, ..., 146, 146, 146],
        [ 94,  96,  96, ..., 153, 151, 151]],

       ...,

       [[199, 199, 199, ..., 104, 103, 103],
        [201, 201, 201, ..., 104, 103, 105],
        [202, 201, 200, ..., 107, 107, 108

In [4]:
L

array([1, 0, 0, ..., 0, 0, 1])

In [5]:
F = F/255

In [6]:
F

array([[[0.48235294, 0.4745098 , 0.4627451 , ..., 0.12156863,
         0.15686275, 0.1372549 ],
        [0.56470588, 0.51764706, 0.44705882, ..., 0.14117647,
         0.20784314, 0.17647059],
        [0.6       , 0.57254902, 0.58823529, ..., 0.19215686,
         0.18431373, 0.21568627],
        ...,
        [0.54117647, 0.4627451 , 0.30588235, ..., 0.54509804,
         0.41960784, 0.21960784],
        [0.55686275, 0.56862745, 0.57647059, ..., 0.63529412,
         0.38431373, 0.18823529],
        [0.58039216, 0.59215686, 0.58039216, ..., 0.48627451,
         0.35294118, 0.21176471]],

       [[0.98823529, 0.98431373, 0.99215686, ..., 0.99607843,
         0.98039216, 0.98431373],
        [0.71764706, 0.83137255, 0.80784314, ..., 0.77647059,
         0.78823529, 0.83137255],
        [0.70196078, 0.99215686, 1.        , ..., 0.99607843,
         0.99215686, 0.99215686],
        ...,
        [0.55686275, 0.5254902 , 0.51372549, ..., 0.43137255,
         0.33333333, 0.55686275],
        [0.5

In [17]:
F = F.reshape(-1,100,100,1)

In [18]:
F.shape

(25000, 100, 100, 1)

In [19]:
from keras.models import Sequential
from keras.layers  import Conv2D,MaxPooling2D,Dense,Flatten,Dropout

In [20]:
model = Sequential()
model.add(Conv2D(64,(3,3),activation = 'relu'))
model.add(MaxPooling2D((2,2)))
model.add(Dropout (0.25))
model.add(Conv2D(64,(3,3),activation = 'relu'))
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128,input_shape = F.shape[1:],activation = 'relu'))
model.add(Dropout(0.5))
model.add(Dense(2,activation = 'softmax'))

In [21]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


In [27]:
model.fit(F,L , epochs=5, validation_split=0.1,batch_size=32)

Train on 22500 samples, validate on 2500 samples
Epoch 1/5
22500/22500 [==============================] - 21s 954us/step - loss: 0.3557 - acc: 0.8452 - val_loss: 0.4244 - val_acc: 0.7980
Epoch 2/5
22500/22500 [==============================] - 21s 944us/step - loss: 0.3191 - acc: 0.8617 - val_loss: 0.4341 - val_acc: 0.8036
Epoch 3/5
22500/22500 [==============================] - 22s 974us/step - loss: 0.2866 - acc: 0.8767 - val_loss: 0.4630 - val_acc: 0.7944
Epoch 4/5
22500/22500 [==============================] - 22s 971us/step - loss: 0.2619 - acc: 0.8907 - val_loss: 0.4242 - val_acc: 0.8080
Epoch 5/5
22500/22500 [==============================] - 22s 956us/step - loss: 0.2334 - acc: 0.9024 - val_loss: 0.5071 - val_acc: 0.7760
